name: CD PUCPR # Continuous delivery
on:
  push:
    branches:
      - main

jobs:
  c_delivery:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: CD (continuous delivery)
        uses: actions/upload-artifact@v4
        with:
          name: formativa3
          path: |
            README.md
            **.py

  c_deploy:
    runs-on: ubuntu-latest
    needs: c_delivery
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: formativa3
      - name: Display structure of downloaded files
        run: ls -R

  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v5
      -
        # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: user/app:latest